language: python
dist: bionic
python:
    - 2.7
    - 3.7
before_install:
    - |
      python --version
      uname -a
      lsb_release -a
      sudo pip install tox
script: tox -v -e $TRAVIS_PYTHON_VERSION -- -v
after_success:
    - .tox/$TRAVIS_PYTHON_VERSION/bin/coveralls
